name: run rs_weekly_89.py

on:
  schedule:
    - cron: '40 9 * * 1,5' # At 09:45 UST (15:15 IST) on Monday and Friday.
  #repository_dispatch: # api trigger
  workflow_dispatch: # manual trigger
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run sip_bot.py
        env:
          GOOGLE_JSON: ${{ secrets.GOOGLE_JSON }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python rs_weekly_89.py --uid 'SJ0281' --wks 'RS_Weekly'
